from typing import Protocol, Iterable, Sequence, List, Mapping
import numpy as np
from uuid import UUID
from .vector import VectorProtocol, VectorDTO

class SearchResultProtocol(Protocol):
    vector_id: UUID
    score: float

class IndexProtocol(Protocol):
    def add(self, vectors: Iterable[VectorProtocol], namespace: str) -> None: ...
    def remove(self, ids: Sequence[UUID], namespace: str) -> None: ...
    def search(self, query: VectorDTO, top_k: int, namespace: str, metric: str) -> List[SearchResultProtocol]: ...
    def rebuild(self, source: Mapping[str, Iterable[VectorProtocol]], metric: str) -> None: ...
    def rebuild(self, metric: str) -> None: ...