from typing import Protocol, Iterable, Sequence, List
from .vector import VectorDTO
from .index import SearchResultProtocol
from uuid import UUID


class QueryProcessorProtocol(Protocol):
    def insert(self, vector: VectorDTO) -> None: ...
    def upsert_many(self, vectors: Iterable[VectorDTO]) -> None: ...
    def find_similar(self, query: VectorDTO, top_k: int, namespace: str = "default", metric: str = "cosine") -> List[SearchResultProtocol]: ...
    def delete(self, ids: Sequence[UUID], namespace: str = "default") -> None: ...